### ISSUE TITLE
Indexing does not delete duplicate data

### ISSUE THREAD

**Issue by missuo** [book-searcher-org/book-searcher#104]
Hello,

When I have multiple different `.csv` files, after I build the index, I find that there seems to be duplicate data with the same **IPFS CID**. I want to know if I can only merge these `.csv`, de-duplicate them myself and build the index again.

Indexed Version: **0.9.0**

![4cbd3ad66ecc93a8ecb4a](https://telegraph.eowo.us/file/4cbd3ad66ecc93a8ecb4a.png)

**Comment by zu1k** [comment]
https://github.com/book-searcher-org/book-searcher#prepare-the-index

### 2. Create index

**You may need to `rm -rf index` first.**

**Comment by zu1k** [comment]
https://github.com/book-searcher-org/book-searcher#raw-data

You better have other ways to maintain the raw data, relational database or even excel can help you to de-duplicate automatically.

Or if you only do incremental indexing each time, the latest development version support merging these scattered segments.

**Comment by missuo** [comment]
@zu1k Thanks, I've de-duplicated it via **MySQL**. Now the merged `.csv` is perfect.
