### ISSUE TITLE
Where do you get the raw csv data?

### ISSUE THREAD

**Issue by ZhoDi** [book-searcher-org/book-searcher#106]

**Comment by Lua12138** [comment]
@zu1k is any news ?

**Comment by chengzyzy** [comment]
rsync  key E36WTBAUFZHSDKW7UNMH24XHNEZO5QLK5T7KBV2SUI4BHMDL5AAUSJK6YSU

**Comment by ZhoDi** [comment]
> Resilio Sync E36WTBAUFZHSDKW7UNMH24XHNEZO5QLK5T7KBV2SUI4BHMDL5AAUSJK6YSU @Lua12138 @ZhoDi

Thank you very much. It has been very useful to me. Will these files be updated or are there any other sources to get them?

**Comment by chengzyzy** [comment]
> > Resilio Sync E36WTBAUFZHSDKW7UNMH24XHNEZO5QLK5T7KBV2SUI4BHMDL5AAUSJK6YSU @Lua12138 @ZhoDi
> 
> Thank you very much. It has been very useful to me. Will these files be updated or are there any other sources to get them? @chengzyzy

just as a backup.
