### ISSUE TITLE
Docker deployment error

### ISSUE THREAD

**Issue by honglet** [book-searcher-org/book-searcher#107]
I run the following on my synology dsm.

sudo RUST_BACKTRACE=1 docker-compose run --rm -v "$PWD:$PWD" -w "$PWD" book-searcher /book-searcher index -f *.csv

But I see the following error

[2023-02-09T19:12:31Z INFO  book_searcher_core::index] Using 4 threads and 17175869176 Bytes to do index
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /source/crates/book-searcher-core/src/index.rs:41:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR: 101

Anything I can look into?

**Comment by zu1k** [comment]
**# Prepare the index: put csv files in the directory, and run the following command to create index**
docker-compose run --rm -v "$PWD:$PWD" -w "$PWD" book-searcher /book-searcher index -f *.csv

**Comment by chwech** [comment]
@zu1k when I run  the command, I got the following error.
```
[root@docker-server book-searcher]# docker-compose run --rm -v "$PWD:$PWD" -w "$PWD" book-searcher /book-searcher index -f *.csv
[2023-02-17T03:18:15Z INFO  book_searcher_core::index] Your system has cpu 1 cores and 314761216 Bytes available
[2023-02-17T03:18:15Z INFO  book_searcher_core::index] Using 1 threads and 209903616 Bytes to do index
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SystemError("Failed to spawn segment updater thread")', /source/crates/book-searcher-core/src/index.rs:38:74
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
