### ISSUE TITLE
IPFS网关总失效问题

### ISSUE THREAD

**Issue by kingjoydom** [book-searcher-org/book-searcher#108]
IPFS网关失效很快，是否可以把https://ipfs-checker.1kbtool.com/集成进系统，动态选择可用的IPFS网关？

**Comment by zu1k** [comment]
This is not a concern of this project, we do not provide files, nor maintain ipfs gateways, these contents are performed by users themselves.

Recently I observed that there are two derivative projects based on this project, which may provide what you need, maybe you can try it:

- https://zbook.lol
- https://clibrary.cn
