### ISSUE TITLE
能否删除自定义网关跳转前缀/ipfs/，以便兼容更多数据库

### ISSUE THREAD

**Issue by bigmouse0001** [book-searcher-org/book-searcher#113]
我试着导入scihub数据，生成index文件后，自定义网关添加类似scihub域名：
https://sci-hub.hkvisa.net
https://sci-hub.mksa.top

![屏幕截图 2023-04-17 194651](https://user-images.githubusercontent.com/119995454/232475308-5b627beb-9e17-4923-acb5-29d3a2cd0dfc.png)

点击下载链接，生成以下url链接（镜像站可正常跳转，但是主站需要删除 /ipfs/ 才可以正常跳转）
https://sci-hub.mksa.top/ipfs/10.1016/j.apsusc.2019.05.102

![屏幕截图 2023-04-17 194935](https://user-images.githubusercontent.com/119995454/232476192-349df89c-e24b-4cd5-a7bf-4d9593e51a14.png)

**测试数据：**[1.csv](https://github.com/book-searcher-org/book-searcher/files/11249832/1.csv)

**问：能不能删除自定义网关前缀中的/ipfs/呢，因为这个后缀可以自己手动加上**

**Comment by zu1k** [comment]
我们没有对其他类型的原始数据进行适配，因此在前端的显示会非常的奇怪。也许后面我们可以将这些内容做成可配置的功能，类似于ElasticSearch的索引模板？目前我不清楚未来的方向。

就当前而言，最简单的方法是修改前端代码：https://github.com/book-searcher-org/book-searcher/blob/a2e55081cebe57a1e64781a99c446db833118890/frontend/src/scripts/ipfs.ts#L28

**Comment by bigmouse0001** [comment]
感谢您的答复，刚刚索引完8000w数据，效果还不错，检索doi秒出准确结果。我的设想是这样的: 

因为book-searcher的下载逻辑是 域名+cid/文件路径，

就目前pilimi，libgen或scihub的公共数据集来看，每个人下载bt种子后，最终得到的文件和保存路径都是相同的。

最终效果就是: 
1. 下载bt种子
2. 导入带文件路径的index文件(每个人都是相同的)
3. 添加自定义网关
4. 运行book-searcher
5. 播种ipfs或bt

zlib，libgen，scihub和读秀都可以实现文件名和文件路径的标准化。

**Comment by bigmouse0001** [comment]
> 就我而言，如果内容不是通过 IPFS 或者其他分布式的方式下载，使用此程序并不是一个好的选择，也许其他通用的索引引擎类似于 ElasticSearch、QuickWit、Meilisearch 会更好。我推荐你尝试一下 Meilisearch，它很简单并且有一个前端界面。
> 
> 当然，你也可以选择基于本项目修改前端代码从而更好的适配你的需求。

IPFS上目前有100万scihub论文，实际大概在400万以上(目前有一个组织正计划将scihub搬运到ipfs上
reddit文章：https://www.reddit.com/r/scihub/comments/12detqs/standard_template_construct_store_and_search_the/
tg频道：https://t.me/+3UReK0DgPeBhOWQy
官网：https://standard--template--construct-org.ipns.dweb.link/#/

它们网站上大约索引了1.28亿论文数据，搜索引擎也是用tantivy构建的。

**Comment by bigmouse0001** [comment]
已删除自定义网关前缀中的/ipfs/，并将查询结果提高为200，详情见→

https://github.com/bigmouse0001/book-searcher

另，就目前pilimi，libgen或scihub的公共数据集来看，每个人下载bt种子后，最终得到的文件和保存路径都是相同的。

最终效果就是: 
1. 下载bt种子
2. 导入带文件路径的index文件(每个人都是相同的)
3. 添加自定义网关
4. 运行book-searcher
5. 播种ipfs或bt

zlib，libgen，scihub和读秀都已经实现文件名和文件路径的标准化。
