### ISSUE TITLE
开放端口后，如何让别人无需任何设置就看到我添加的自定义网关？

### ISSUE THREAD

**Issue by bigmouse0001** [book-searcher-org/book-searcher#114]
我已经修改前端代码，并且成功发布新的release版本。现在将ipfs_cid列更换为doi后，可以正常跳转scihub镜像站。

但是，用内网穿透开放7070端口后，发现其他主机看不到我在localhost添加的自定义网关。

问: 我设置好自定义网关，开放端口后能不能让别人也看得到？并且假如我在本地更新了自定义网关，别人访问网站的时候也能同步更新。

**Comment by zu1k** [comment]
https://github.com/book-searcher-org/book-searcher/issues/38#issuecomment-1368408663
