### ISSUE TITLE
能否增加armv7，arm64架构的docker镜像

### ISSUE THREAD

**Issue by bigmouse0001** [book-searcher-org/book-searcher#116]
如题，咸鱼买一个50r的机顶盒(armv架构，4核1+8g起步，可扩展)，月功耗不到1度电。

1. 我在github上改动dockerfile后，将[docker.yml文件第46行修改为](https://github.com/bigmouse0001/book-searcher/commit/cdad8644dec39b64d8e37bcf6e58eac5b1fe18fe)：`platforms: linux/amd64,linux/arm64`

   Github Actions[自动构建docker镜像失败](https://github.com/bigmouse0001/book-searcher/actions/runs/4921837459/jobs/8792060220)：报错

> `buildx failed with: ERROR: failed to solve: process "/dev/.buildkit_qemu_emulator /bin/sh -c cd /source/frontend && npm install --legacy-peer-deps && npm run build" did not complete successfully: exit code: 139`

2. 我按照[这份成功编译arm架构镜像的指南](https://dejavu.moe/posts/build-multiarch-docker-image/)，在armv7，ubuntu系统机顶盒上开始编译后，在上述相同位置报错。

另外，在arm架构，ubuntu20.04系统的机顶盒中，直接用终端输入./book-searcher run，可以成功运行下述程序：

> [book-searcher-armv7-unknown-linux-gnueabihf.tar.gz](https://github.com/bigmouse0001/book-searcher/releases/download/0.9.1.1/book-searcher-armv7-unknown-linux-gnueabihf.tar.gz)
> [book-searcher-aarch64-unknown-linux-musl.tar.gz](https://github.com/bigmouse0001/book-searcher/releases/download/0.9.1.1/book-searcher-aarch64-unknown-linux-musl.tar.gz)

**Comment by zu1k** [comment]
已增加

**Comment by bigmouse0001** [comment]
谢谢~
