### ISSUE TITLE
分词系统能否增加对更多语言的支持？

### ISSUE THREAD

**Issue by bigmouse0001** [book-searcher-org/book-searcher#117]
如题，本程序的各种功能都已经非常完美了，但还有一个不足之处，即分词系统仅支持少数几种语言。目前外文数据库中，占比较大的依次是：
1. 英语，2. 俄语，3. 中文

英语和中文支持比较良好，但是俄语和阿拉伯语、希腊语、希伯来语、印度语等小语种几乎匹配不到。然而，tantivy的使用文档列举了20多种语言的的分词器。

所以我想问一下，在当前的代码架构内，能不能为tantivy引擎添加更多语言的分词器呢？如果有的话，是否有一个通用的新增模板？

谢谢！

**Comment by zu1k** [comment]
拉丁语系的语言默认都是支持的，CJK目前仅支持中文，还有一些其他语言可能不是本应用的用户

**Comment by bigmouse0001** [comment]
感谢回复，了解！
