### ISSUE TITLE
前端界面可以预览封面 cover_url了吗？

### ISSUE THREAD

**Issue by bigmouse0001** [book-searcher-org/book-searcher#121]
在readme中注意到，元数据增加了字段: 

- cover_url, 
- md5

目前已知的可下载/调用的封面数据:

libgen(可下载)
zlib(可下载)
读秀(可调用)

**Comment by zu1k** [comment]
Yes, as long as you provide the accessible image url, the frontend will display it.

**Comment by bigmouse0001** [comment]
That's great！May I ask you to release a csv-rawdata sample with cover_url？so that I can build my own index by  imitating your sample. Thanks~

**Comment by bigmouse0001** [comment]
是不是需要重新构建新版本程序呢？

下载0.91版本的exe，对测试数据生成索引，搜索结果里面没有对应的封面预览图。

测试数据打包：
[book-searcher-0.91.zip](https://github.com/book-searcher-org/book-searcher/files/12111798/book-searcher-0.91.zip)

csv截图：
![image](https://github.com/book-searcher-org/book-searcher/assets/119995454/e52e6d6e-9f8e-4f80-a5b9-1c788026fc8a)

**Comment by bigmouse0001** [comment]
ok，成功了！

![image](https://github.com/book-searcher-org/book-searcher/assets/119995454/892af52a-6be9-4ce3-86c4-8f0ec3d8725c)
