### ISSUE TITLE
desktop新版程序bug，保存索引，创建索引，浏览按钮失效，

### ISSUE THREAD

**Issue by bigmouse0001** [book-searcher-org/book-searcher#123]
1. 输入索引目录，点保存一直转圈(去掉双引号也是这样
2. 点浏览按钮没反应
![image](https://github.com/book-searcher-org/book-searcher/assets/119995454/a37bea91-44a4-4663-9e3e-668fabcb7966)

3. 创建索引，点创建没反应
4. 点浏览按钮没反应
![image](https://github.com/book-searcher-org/book-searcher/assets/119995454/be8df243-a8cc-4ed3-8829-0d617961b3ea)

**Comment by zu1k** [comment]
@mtfcd Do you have time to figure out this?

**Comment by mtfcd** [comment]
@bigmouse0001 可以提供一下你的构建工具和依赖的版本吗？

**Comment by bigmouse0001** [comment]
> @bigmouse0001 可以提供一下你的构建工具和依赖的版本吗？

额。。。我克隆仓库以后用github action自动构建的，然后下载的Windows-desktop版

**Comment by bigmouse0001** [comment]
我是克隆仓库以后用github action自动构建的，没有改动代码。下载Windows-desktop版，打开发现了这个问题，具体是：

- [Release界面](https://github.com/bigmouse0001/book-searcher/releases/tag/0.9.2)
- [测试版本](https://github.com/bigmouse0001/book-searcher/releases/download/0.9.2/Book.Searcher_1.1.0_x64_en-US.msi)
