### ISSUE TITLE
[Bug] When the window is at a certain width, it will display overlapping.

### ISSUE THREAD

**Issue by missuo** [book-searcher-org/book-searcher#144]
As shown in the following image, overlapping occurs when the window is not large enough to display.

![Xnip2023-10-14_22-31-35](https://r2.qwq.mx/files/Xnip2023-10-14_22-31-35.png)

![Xnip2023-10-14_22-31-26](https://r2.qwq.mx/files/Xnip2023-10-14_22-31-26.png)

**Comment by zu1k** [comment]
@abisuq Do you have time to fix this?

**Comment by missuo** [comment]
The problem is indeed fixed in Chinese and English, but I tried French and Italian and it's still there.

![91bde8a2b7898cb2ca1cb](https://i3.wp.com/telegra.ph/file/91bde8a2b7898cb2ca1cb.png)

![74df8ccd528a8466c7e2d](https://i3.wp.com/telegra.ph/file/74df8ccd528a8466c7e2d.png)

**Comment by zu1k** [comment]
The width is enough to display the content.

Maybe the description is too long. We need to shorten the title.

**Comment by zu1k** [comment]
@missuo Can you fix this ?

**Comment by missuo** [comment]
> The width is enough to display the content.
> 
> Maybe the description is too long. We need to shorten the title.

If the title is modified, I don't know if it will affect the understanding of the title. After all, this is in French and Italian, which I don't understand.

**Comment by zu1k** [comment]
Just do it, if it's not suitable the French and Italians will correct it.
