### ISSUE TITLE
[BUG] Detail card title format issue

### ISSUE THREAD

**Issue by zu1k** [book-searcher-org/book-searcher#153]
When the title is too long, overflow will occur on the large screen.

![image](https://github.com/book-searcher-org/book-searcher/assets/42370281/da59eebe-b78c-4d41-b5db-9ffc1c49cc3c)

On small screen, the title and button on the right are crowded together.

![image](https://github.com/book-searcher-org/book-searcher/assets/42370281/3f143153-e98f-4254-8212-af1ad1a619a5)

We expect that on small screens, if the title is too long, the button should wrap

**Comment by kaichii** [comment]
@zu1k Title should be 1 line or not when the button wraps?

<img width="1062" alt="image" src="https://github.com/book-searcher-org/book-searcher/assets/49476516/af8158b1-3982-49fa-84bc-96c650263318">

or

<img width="1044" alt="image" src="https://github.com/book-searcher-org/book-searcher/assets/49476516/57442da8-af07-42fe-8568-7ea1ddb23b9a">

**Comment by zu1k** [comment]
Under detail card it need to display the full title

**Comment by zu1k** [comment]
@kaichii There's already a PR working on this one bug, maybe we can collaborate to avoid duplication of effort!
