### ISSUE TITLE
[feature] Make search results directly linkable

### ISSUE THREAD

**Issue by nileshtrivedi** [book-searcher-org/book-searcher#50]
First of all, kudos for building this fantastic tool! 

I created [LearnAwesome.org](https://learnawesome.org/) ([github](https://github.com/learn-awesome/learndb)) and was looking for ways to get IPFS identifiers for books by their ISBN but struggled because Libgen DB dumps that I could find only had MD5 hashes and not IPFS cids. Great job for putting this together! 👏 

Here's a feature request: It would be great to have specific search results directly linkable. My project linked above is an attempt to build an easily navigable map of curated learning resources on all topics. It's not limited to books but books are definitely an important media type. There's no intention to add every single book in our catalog though. On our book page, we link to the search results page for OpenLibrary, GoodReads etc. It would be great to be link to your tool as well.

Aside: If you're thinking of building an Apple iBooks-like interface - which needs a lot of work on topic taxonomy, expert reviews etc - thenI suggest you look at my project in depth. It already looks quite nice:

<img width="1605" alt="image" src="https://user-images.githubusercontent.com/19304/210029792-1bf518a9-e1f2-4e29-b267-d5183a4a57e7.png">

**Comment by Wybxc** [comment]
We will not provide an official public website. 

Instead, users need to use their own deployment, which means there is no stable URL that can be linked to.
