### ISSUE TITLE
[feat] create index on the desktop version

### ISSUE THREAD

**Issue by zu1k** [book-searcher-org/book-searcher#76]
Now we only support using cli to create an index.

We need to add the function of graphical index creation on the desktop.

**Comment by jusanyuan** [comment]
大神能不能出一个自己桌面端创建索引的教程呢

**Comment by zu1k** [comment]
> 大神能不能出一个自己桌面端创建索引的教程呢

We haven't added this function yet.

**Comment by jusanyuan** [comment]
那docker端可以自己创建索引吗？我看你们之后也不提供索引，希望能提供具体索引的方法，一遍我们自己也能索引。愿后续能够能够支持

**Comment by zu1k** [comment]
> 那docker端可以自己创建索引吗？我看你们之后也不提供索引，希望能提供具体索引的方法，一遍我们自己也能索引。愿后续能够能够支持

We already have a tutorial. Read the README please.

**Comment by vyv2000** [comment]
Hello, where can I download the index file, I've been looking for a long time and can't find it
thx

**Comment by vyv2000** [comment]
Wish there was a dock-compose arm version

**Comment by zu1k** [comment]
> Wish there was a dock-compose arm version

Please don't discuss irrelevant topics.

**Comment by zu1k** [comment]
> Hello, where can I download the index file, I've been looking for a long time and can't find it
> thx

We don't provide this.

**Comment by zu1k** [comment]
@Wybxc  Do you have time for this?

**Comment by Wybxc** [comment]
> @Wybxc Do you have time for this?

Currently not.

**Comment by mtfcd** [comment]
May I try this? I have read the front-end and the desktop code. but I have some questions. I find the the desktop crate use tauri version of 2.0 but the front end use 1.4, is this intentionally? and what's the tauri cli version? because I cant make get the `tauri/api/dialog/open` function work.

**Comment by zu1k** [comment]
I hope you can use the latest version and make the compilation pass.

- [tauri@2.0.0-alpha.10](https://crates.io/crates/tauri/2.0.0-alpha.10)
- [tauri-build@2.0.0-alpha.6](https://crates.io/crates/tauri-build/2.0.0-alpha.6)
- [@tauri-apps/cli@next](https://www.npmjs.com/package/@tauri-apps/cli/v/2.0.0-alpha.10)
- [@tauri-apps/api@next](https://www.npmjs.com/package/@tauri-apps/api/v/2.0.0-alpha.5)

In the [latest version of tauri](https://docs.rs/crate/tauri/2.0.0-alpha.10/features), the `dialog-open` and `shell-open` features we [used before](https://docs.rs/crate/tauri/2.0.0-alpha.6/features#dialog-open) were removed, and I [removed them in order for the CI to pass](https://github.com/book-searcher-org/book-searcher/commit/b09e69aa2ecb2dc0a0aa7624a534ff11478b572e), so the current version of the desktop code is broken.

I will assigne this issue to you. Please investigate how this can be done in the latest tauri and fix the code.

**Comment by zu1k** [comment]
#120
