### ISSUE TITLE
no download url in new version of project & index (v0.9)?

### ISSUE THREAD

**Issue by godlockin** [book-searcher-org/book-searcher#79]
i've tried several keywords include different scenarios/categories, but only summary and base info displayed without download url :(

I tried the "old" versions with the same keywords, and they could afford the download url, so, how can i get the download url in newer versions?

**Comment by zu1k** [comment]
#38

**Comment by godlockin** [comment]
any format/data structure different among 'old' version and 'new' version? is it able to load the 'old' index file into 'new' docker images?
