### ISSUE TITLE
[bug] Some book title searches return no results.

### ISSUE THREAD

**Issue by missuo** [book-searcher-org/book-searcher#83]
After this commit [feat: T2S before jieba tokenize](https://github.com/book-searcher-org/book-searcher/commit/3dff5e62dc89b4cfd187f783ef186d4ebb9264f3), some title searches did not return any content, but everything was fine in version 0.8.0. 

**Affected titles include: `小王子`.**

**Comment by zu1k** [comment]
I have test it, everything works fine.

**Comment by zu1k** [comment]
Maybe you haven't regenerated the index.

This new version has not been officially released yet. If you want to use it, you need to be responsible for it.

**Comment by missuo** [comment]
I am using the 0.8.0 index, which may be the cause of the bug.

**Comment by rdshoep** [comment]
I have the some problem with 0.8.1 and `zlib-searcher/index`‘s index data.

This problem will appear at searching **title** with **more than** two chinese letters.

**Comment by zu1k** [comment]
![image](https://user-images.githubusercontent.com/42370281/211950231-f38e672f-1a71-4767-9123-32844a7a8205.png)
![image](https://user-images.githubusercontent.com/42370281/211950294-c924a838-719b-4868-b224-d87e4d57e2bc.png)

Can't reproduce
