### ISSUE TITLE
《中国农民调查》 can not search by book search with index data, but can be found by telegram bot  https://t.me/ZLibrary1_bot

### ISSUE THREAD

**Issue by joostshao** [book-searcher-org/book-searcher#85]
《中国农民调查》 can not search by book search with index data, but can be found by telegram bot  https://t.me/ZLibrary1_bot
what happend to the index data ?

**Comment by joostshao** [comment]
how to create csv files ?

**Comment by zu1k** [comment]
We don't provide index, don't ask us for feedback.

The csv file is plain text and can be created through the text editor.

**Comment by zu1k** [comment]
And the book you mentioned can be searched normally under our test data set.
