### ISSUE TITLE
Docker 部署失败

### ISSUE THREAD

**Issue by Leexiaobu** [book-searcher-org/book-searcher#86]
log：
```
Pulling book-searcher (ghcr.io/book-searcher-org/book-searcher:latest)...
latest: Pulling from book-searcher-org/book-searcher
6e3729cf69e0: Pull complete
cc05ff5d6af9: Pull complete
Digest: sha256:ac6d5a88cfab8a5c896149123d48cef571388aa12a7d4f2b87147b81a56785f9
Status: Downloaded newer image for ghcr.io/book-searcher-org/book-searcher:latest
Creating book-searcher_book-searcher_1 ... done
Attaching to book-searcher_book-searcher_1
book-searcher_1  | [2023-01-11T02:55:36Z INFO  book_searcher] book-searcher webserver started!
book-searcher_1  | [2023-01-11T02:55:36Z INFO  book_searcher] AppState init!
book-searcher_1  | [2023-01-11T02:55:36Z INFO  tantivy::indexer::segment_updater] save metas
book-searcher_1  | [2023-01-11T02:55:36Z INFO  actix_server::builder] Starting 4 workers
book-searcher_1  | [2023-01-11T02:55:36Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
book-searcher_1  | thread 'main' panicked at 'Cannot spawn Arbiter's thread: "actix-rt|system:0|arbiter:0". Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.7.0/src/arbiter.rs:153:17
book-searcher_1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
添加 "RUST_BACKTRACE=full" :
```
Recreating book-searcher_book-searcher_1 ... done
Attaching to book-searcher_book-searcher_1
book-searcher_1  | [2023-01-11T03:01:45Z INFO  book_searcher] book-searcher webserver started!
book-searcher_1  | [2023-01-11T03:01:45Z INFO  book_searcher] AppState init!
book-searcher_1  | [2023-01-11T03:01:45Z INFO  actix_server::builder] Starting 4 workers
book-searcher_1  | [2023-01-11T03:01:45Z INFO  actix_server::server] Actix runtime found; starting in Actix runtimebook-searcher_1  | thread 'main' panicked at 'Cannot spawn Arbiter's thread: "actix-rt|system:0|arbiter:0". Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.7.0/src/arbiter.rs:153:17
book-searcher_1  | stack backtrace:
book-searcher_1  |    0:     0x55a56ec577bc - <unknown>
book-searcher_1  |    1:     0x55a56eb3c48e - <unknown>
book-searcher_1  |    2:     0x55a56ec32564 - <unknown>
book-searcher_1  |    3:     0x55a56ec58f7f - <unknown>
book-searcher_1  |    4:     0x55a56ec58b7f - <unknown>
book-searcher_1  |    5:     0x55a56ec59c2f - <unknown>
book-searcher_1  |    6:     0x55a56ec596e4 - <unknown>
book-searcher_1  |    7:     0x55a56ec5964c - <unknown>
book-searcher_1  |    8:     0x55a56ec59621 - <unknown>
book-searcher_1  |    9:     0x55a56e9594b2 - <unknown>
book-searcher_1  |   10:     0x55a56ea3a819 - <unknown>
book-searcher_1  |   11:     0x55a56ea5344a - <unknown>
book-searcher_1  |   12:     0x55a56ea33765 - <unknown>
book-searcher_1  |   13:     0x55a56ea2fd38 - <unknown>
book-searcher_1  |   14:     0x55a56e9e8688 - <unknown>
book-searcher_1  |   15:     0x55a56ea03901 - <unknown>
book-searcher_1  |   16:     0x55a56e9cc8b3 - <unknown>
book-searcher_1  |   17:     0x55a56ea12e99 - <unknown>
book-searcher_1  |   18:     0x7f8b58418d90 - <unknown>
book-searcher_1  |   19:     0x7f8b58418e40 - __libc_start_main
book-searcher_1  |   20:     0x55a56e97c6ba - <unknown>
book-searcher_1  |   21:                0x0 - <unknown>
```

**Comment by zu1k** [comment]
What's your docker version? Upgrade your docker

**Comment by Elity** [comment]
> What's your docker version? Upgrade your docker

I also get a similar error when using the built-in docker on QNAP, version: Docker version 20.10.17-qnap5, build 0474f29.

**Comment by zu1k** [comment]
> > What's your docker version? Upgrade your docker
> 
> I also get a similar error when using the built-in docker on QNAP, version: Docker version 20.10.17-qnap5, build 0474f29.
> 
> ```shell
> [admin@Q-NAS book-searcher]# docker-compose run --rm -v "$PWD:$PWD" -w "$PWD" book-searcher /book-searcher index -f *.csv
> Creating book-searcher_book-searcher_run ... done
> [2023-01-11T05:23:43Z INFO  book_searcher_core::index] Your system has cpu 4 cores and 4145803264 Bytes available
> [2023-01-11T05:23:43Z INFO  book_searcher_core::index] Using 4 threads and 8291606528 Bytes to do index
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /source/crates/book-searcher-core/src/index.rs:40:42
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ERROR: 101
> ```

@xxchan

**Comment by zu1k** [comment]
> > What's your docker version? Upgrade your docker
> 
> I also get a similar error when using the built-in docker on QNAP, version: Docker version 20.10.17-qnap5, build 0474f29.
> 
> ```shell
> [admin@Q-NAS book-searcher]# docker-compose run --rm -v "$PWD:$PWD" -w "$PWD" book-searcher /book-searcher index -f *.csv
> Creating book-searcher_book-searcher_run ... done
> [2023-01-11T05:23:43Z INFO  book_searcher_core::index] Your system has cpu 4 cores and 4145803264 Bytes available
> [2023-01-11T05:23:43Z INFO  book_searcher_core::index] Using 4 threads and 8291606528 Bytes to do index
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /source/crates/book-searcher-core/src/index.rs:40:42
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ERROR: 101
> ```

Which csv file do you want to index?

**Comment by Elity** [comment]
My mistake, I didn't read the documentation carefully and didn't prepare the index file beforehand, but now it has been successfully launched.

**Comment by Leexiaobu** [comment]
> What's your docker version? Upgrade your docker

Docker version 20.10.9, build c2ea9bc

**Comment by zu1k** [comment]
@Leexiaobu What's your linux kernel version?

**Comment by zu1k** [comment]
Maybe you can try to start container with `with --privileged --security-opt="seccomp=unconfined"`

**Comment by Leexiaobu** [comment]
> Maybe you can try to start container with `--privileged --security-opt="seccomp=unconfined"`
> 

谢谢,加了--privileged 就可以启动了,
当前的yml文件内容如下:
```
version: '3'

services:
  book-searcher:
    image: ghcr.io/book-searcher-org/book-searcher:latest
    restart: always
    ports:
      - "7070:7070"
    volumes:
      - ./index:/index
    privileged: true
```
