### ISSUE TITLE
The version in MacOS dmg file is still 0.8.1

### ISSUE THREAD

**Issue by hustnzj** [book-searcher-org/book-searcher#88]
I have downloaded the latest dmg file. 
<img width="603" alt="image" src="https://user-images.githubusercontent.com/27875723/212210375-f77b6414-969d-493c-9978-260af31a3750.png">

But after I installed it, the version is still 0.8.1 and the `preview` function is not available yet.
<img width="284" alt="image" src="https://user-images.githubusercontent.com/27875723/212210251-ebbc7acd-72d8-48d7-8052-d518205c74a8.png">
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/27875723/212210291-81e227f7-118f-489a-bb7c-aa17c94c62b0.png">

Thank you.

**Comment by zu1k** [comment]
I forgot to change the version number because I temporarily decided to release a new version. 

There is no preview function because there is no specified IPFS gateway.

**Comment by hustnzj** [comment]
@zu1k Thank you very much.
