### ISSUE TITLE
希望能提供一份索引的样式

### ISSUE THREAD

**Issue by myliumer** [book-searcher-org/book-searcher#89]
提供一份简单的样式即可，自己生成几次都没搞定。

**Comment by zu1k** [comment]
You should prepare your books metainfo, a `csv` file with the following fields:

`id, title, author, publisher, extension, filesize, language, year, pages, isbn, ipfs_cid`

**example.csv**

```csv
1,活着,余华,作家出版社,epub,654944,other,2021,"","750636543X,9787506365437",bafk2bzaceddo2w5otshhsl57a4b3lzpqdmpw4bnkhsppbnexb5fck4xeiko2o
```

Then index it:

```
./book-searcher index -f example.csv
```
