### ISSUE TITLE
Memory map length overflows isize on rpi3 armv7

### ISSUE THREAD

**Issue by cascafico** [book-searcher-org/book-searcher#91]
Compiled version in use:
[book-searcher-armv7-unknown-linux-gnueabihf](https://github.com/book-searcher-org/book-searcher/releases/download/0.8.3/book-searcher-armv7-unknown-linux-gnueabihf.tar.gz)

```
pi@rpi3:~book-searcher $ uname -a
Linux rpi3 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

pi@rpi3:~/book-searcher $ ./book-searcher -V
book-searcher 0.8.3

pi@rpi3:~/book-searcher $ curl 127.0.0.1:7070/search?query=title:leopardi

thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: OpenReadError(IoError { io_error: Custom { kind: InvalidData, error: "memory map length overflows isize" }, filepath: "/home/pi/book-searcher/index/143103b385254387a5aa1264f5ef3d6e.store" })', crates/book-searcher-core/src/search.rs:6:42

curl: (52) Empty reply from server
```

**Comment by yihong0618** [comment]
This is a bit heavy for a Raspberry Pi

**Comment by zu1k** [comment]
Maybe you should try 64bit version linux, and use the aarch64 version binary.

**Comment by cascafico** [comment]
> This is a bit heavy for a Raspberry Pi

I happly used 0.8.1 executable and index until last week. I had amazingly fast curl responses.

**Comment by yihong0618** [comment]
I just have a `3B` will test later

**Comment by zu1k** [comment]
> Edit: I just tried executable 0.8.1 with 0.8.3 index and I have the same issue.

Maybe `index` data invalid, where did you get it?

**Comment by cascafico** [comment]
> > Edit: I just tried executable 0.8.1 with 0.8.3 index and I have the same issue.

> Maybe index data invalid, where did you get it?

[index_none_0.8.3.zip](https://ipfs.io/ipfs/bafybeifgefvchbovm6d44z3ruaxdoopgmka4gjgvenv4zvw4ektmfkewf4/index_none_0.8.3.zip)
> You're better off generating your own `index` than downloading one provided by others.

I've just run [windows version](https://github.com/book-searcher-org/book-searcher/releases/download/0.8.3/book-searcher-x86_64-pc-windows-gnu.zip) on same index folder and it works flawlessy

**Comment by zu1k** [comment]
> Maybe you should try 64bit version linux, and use the aarch64 version binary.

You should try this.

**Comment by cascafico** [comment]
> > Maybe you should try 64bit version linux, and use the aarch64 version binary.
> 
> You should try this.
> 
> 32bit is a legacy for those 32bit machine, but rpi3 supports 64bit, you just need to install a 64bit system.

Thanks, raspberry is in remote location: I will try 64bit OS ASAP.

**Comment by zu1k** [comment]
And if you still want to use 32bit system, the index should be less than 2GB, a better compression algorithm should be chosen，such as `brotli`.

**Comment by cascafico** [comment]
Thanks for your precious suggestion, I will try later. Anyway, when I will
be able to access phisically the device, I will take the chance to renew
rpi3 OS :-)

Il mer 18 gen 2023, 12:42 zu1k ***@***.***> ha scritto:

**Comment by zu1k** [comment]
I'm going to close this for long time no update, you can restart if the problem still exists.
