### ISSUE TITLE
是否可以提供关于复杂搜索的使用示例及方法

### ISSUE THREAD

**Issue by Hpeox** [book-searcher-org/book-searcher#95]
![图片](https://user-images.githubusercontent.com/89294013/213840126-f4c43fa2-4a88-4667-87e7-7bb527a8c927.png)
似乎没有地方提到我应该使用怎样的语法进行复杂搜索故希望作者们可以做一个简单的解答
谢谢大佬们

**Comment by zu1k** [comment]
https://github.com/book-searcher-org/book-searcher#original-search-api

https://quickwit.io/docs/reference/query-language/

https://github.com/quickwit-oss/tantivy/tree/main/query-grammar
