### ISSUE TITLE
为什么用命令行创建的index数据不能用于桌面版？

### ISSUE THREAD

**Issue by bigmouse0001** [book-searcher-org/book-searcher#97]
0.9.0版本发布页

①  桌面版：Book-Searcher-desktop_0.9.0_x64.msi
②  命令行版：book-searcher-x86_64-pc-windows-gnu.zip
③  原始数据：zlib index.csv（20220111），libgen index.csv（20220113），libgen fiction index.csv（20220113）

背景描述：
1. win10系统，用cmd对以上原始数据生成index文件夹，获得22 个文件，共1.85 GB，1,990,785,668 字节
2. cmd界面执行book searcher.exe run
3. 浏览器成功打开webui界面，输入关键词，可获得检索内容

问题：将以上index文件夹复制至desktop版根目录，打开desktop程序，输入关键词，检索不到任何信息。

**Comment by zu1k** [comment]
Please check the readme for the desktop version

**Comment by bigmouse0001** [comment]
根据readme，我已经成功生成index文件。但该文件无法在desktop version使用。
