### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by dqkj666** [book-searcher-org/book-searcher#98]
The following problem occurred when using metadata to build a new index on win10

![image](https://user-images.githubusercontent.com/105642825/214194661-975d99e6-3f10-4e0f-a35e-341a0606ec1e.png)
![image](https://user-images.githubusercontent.com/105642825/214194695-97d079ba-831a-4f61-a657-d1c8a6729dbe.png)

**Comment by zu1k** [comment]
read readme
